 include_task---
- name: Configure apache2 using multiple chpld playbooks
  hosts: all
  tasks:
    - name: Call multiple child playbooks
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
