---
- name: Error Handling or Exception handling in Ansible
  hosts: all
  tasks:
    - block:
       - name: Install using apt on ubuntu servers
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: Install using yum on redhat servers
          yum:
            name: git
            state: present
            update_cache: yes
      always:
        - name: Clone remote github code
          git:
            repo: https://github.com/IntelliqDevops/maven.git
            dest: /tmp/maven
...
