---
- name: Install/uninstall s/w applications
  hosts: all
  vars:
    - a: tomcat10
    - b: present
    - c: yes
  tasks:
    - name: Install/Unstall of s/w
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
